# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  border: single
  windowSize: normal
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
os:
  editPreset: 'nvim'

